<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Packet\**" />
    <Compile Remove="protoc-21.12-osx-aarch_64\**" />
    <Compile Remove="ServerCore\**" />
    <EmbeddedResource Remove="Packet\**" />
    <EmbeddedResource Remove="protoc-21.12-osx-aarch_64\**" />
    <EmbeddedResource Remove="ServerCore\**" />
    <None Remove="Packet\**" />
    <None Remove="protoc-21.12-osx-aarch_64\**" />
    <None Remove="ServerCore\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="ServerSession.cs" />
    <Compile Remove="SessionManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DummyClient.csproj.lscache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServerCore\ServerCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
  </ItemGroup>

</Project>
