// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpXCgVNc2dJZBIPCgtNU0dfSURfTk9O",
            "RRAAEhUKEFBLVF9DX0VOVEVSX0dBTUUQ6gcSFQoQUEtUX1NfRU5URVJfR0FN",
            "RRDrBxIPCgpQS1RfQ19NT1ZFEPAHKm0KCk9iamVjdFR5cGUSFAoQT0JKRUNU",
            "X1RZUEVfTk9ORRAAEhgKFE9CSkVDVF9UWVBFX0NSRUFUVVJFEAESGgoWT0JK",
            "RUNUX1RZUEVfUFJPSkVDVElMRRACEhMKD09CSkVDVF9UWVBFX0VOVhADKnIK",
            "DENyZWF0dXJlVHlwZRIWChJDUkVBVFVSRV9UWVBFX05PTkUQABIYChRDUkVB",
            "VFVSRV9UWVBFX1BMQVlFUhABEhkKFUNSRUFUVVJFX1RZUEVfTU9OU1RFUhAC",
            "EhUKEUNSRUFUVVJFX1RZUEVfTlBDEAMqMAoHRW52VHlwZRIRCg1FTlZfVFlQ",
            "RV9OT05FEAASEgoORU5WX1RZUEVfRklFTEQQASpoCgpQbGF5ZXJUeXBlEhQK",
            "EFBMQVlFUl9UWVBFX05PTkUQABIWChJQTEFZRVJfVFlQRV9LTklHSFQQARIU",
            "ChBQTEFZRVJfVFlQRV9NQUdFEAISFgoSUExBWUVSX1RZUEVfQVJDSEVSEAMq",
            "vgEKDFN0YXRlTWFjaGluZRIWChJTVEFURV9NQUNISU5FX05PTkUQABIWChJT",
            "VEFURV9NQUNISU5FX0lETEUQARIYChRTVEFURV9NQUNISU5FX1BBVFJPTBAC",
            "EhgKFFNUQVRFX01BQ0hJTkVfTU9WSU5HEAMSGQoVU1RBVEVfTUFDSElORV9D",
            "QVNUSU5HEAQSFwoTU1RBVEVfTUFDSElORV9TS0lMTBAFEhYKElNUQVRFX01B",
            "Q0hJTkVfREVBRBAGKlQKCVNraWxsVHlwZRIOCgpTS0lMTF9OT05FEAASDgoK",
            "U0tJTExfQVVUTxABEhQKEFNLSUxMX1BST0pFQ1RJTEUQAhIRCg1TS0lMTF9B",
            "T0VfRE9UEAMqSgoJQ2FzdFN0YXRlEg4KCkNBU1RfU1RBUlQQABIPCgtDQVNU",
            "X0NBTkNFTBABEhAKDENBU1RfU1VDQ0VTUxACEgoKBkFDVElPThADQhuqAhhH",
            "b29nbGUuUHJvdG9idWYuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MsgId), typeof(global::Google.Protobuf.Protocol.ObjectType), typeof(global::Google.Protobuf.Protocol.CreatureType), typeof(global::Google.Protobuf.Protocol.EnvType), typeof(global::Google.Protobuf.Protocol.PlayerType), typeof(global::Google.Protobuf.Protocol.StateMachine), typeof(global::Google.Protobuf.Protocol.SkillType), typeof(global::Google.Protobuf.Protocol.CastState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("MSG_ID_NONE")] None = 0,
    [pbr::OriginalName("PKT_C_ENTER_GAME")] PktCEnterGame = 1002,
    [pbr::OriginalName("PKT_S_ENTER_GAME")] PktSEnterGame = 1003,
    [pbr::OriginalName("PKT_C_MOVE")] PktCMove = 1008,
  }

  public enum ObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("OBJECT_TYPE_CREATURE")] Creature = 1,
    [pbr::OriginalName("OBJECT_TYPE_PROJECTILE")] Projectile = 2,
    [pbr::OriginalName("OBJECT_TYPE_ENV")] Env = 3,
  }

  public enum CreatureType {
    [pbr::OriginalName("CREATURE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("CREATURE_TYPE_PLAYER")] Player = 1,
    [pbr::OriginalName("CREATURE_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("CREATURE_TYPE_NPC")] Npc = 3,
  }

  public enum EnvType {
    [pbr::OriginalName("ENV_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ENV_TYPE_FIELD")] Field = 1,
  }

  public enum PlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_KNIGHT")] Knight = 1,
    [pbr::OriginalName("PLAYER_TYPE_MAGE")] Mage = 2,
    [pbr::OriginalName("PLAYER_TYPE_ARCHER")] Archer = 3,
  }

  public enum StateMachine {
    [pbr::OriginalName("STATE_MACHINE_NONE")] None = 0,
    [pbr::OriginalName("STATE_MACHINE_IDLE")] Idle = 1,
    [pbr::OriginalName("STATE_MACHINE_PATROL")] Patrol = 2,
    [pbr::OriginalName("STATE_MACHINE_MOVING")] Moving = 3,
    [pbr::OriginalName("STATE_MACHINE_CASTING")] Casting = 4,
    [pbr::OriginalName("STATE_MACHINE_SKILL")] Skill = 5,
    [pbr::OriginalName("STATE_MACHINE_DEAD")] Dead = 6,
  }

  public enum SkillType {
    [pbr::OriginalName("SKILL_NONE")] SkillNone = 0,
    [pbr::OriginalName("SKILL_AUTO")] SkillAuto = 1,
    [pbr::OriginalName("SKILL_PROJECTILE")] SkillProjectile = 2,
    [pbr::OriginalName("SKILL_AOE_DOT")] SkillAoeDot = 3,
  }

  public enum CastState {
    [pbr::OriginalName("CAST_START")] CastStart = 0,
    [pbr::OriginalName("CAST_CANCEL")] CastCancel = 1,
    [pbr::OriginalName("CAST_SUCCESS")] CastSuccess = 2,
    [pbr::OriginalName("ACTION")] Action = 3,
  }

  #endregion

}

#endregion Designer generated code
